args <- commandArgs(FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
script_dir <- if (length(file_arg) > 0) dirname(normalizePath(file_arg[[1]])) else file.path(getwd(), "scripts_R")
source(file.path(script_dir, "11_figure_1_baseline_heterogeneity.R"))
source(file.path(script_dir, "12_figure_2_country_strategy_prioritization.R"))
source(file.path(script_dir, "13_figure_3_endpoint_dependence.R"))
source(file.path(script_dir, "14_figure_4_resistance_conditioned_control.R"))
